/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface StatusBarComponent {
        "height": string;
        "width": string;
    }
}
declare global {
    interface HTMLStatusBarComponentElement extends Components.StatusBarComponent, HTMLStencilElement {
    }
    var HTMLStatusBarComponentElement: {
        prototype: HTMLStatusBarComponentElement;
        new (): HTMLStatusBarComponentElement;
    };
    interface HTMLElementTagNameMap {
        "status-bar-component": HTMLStatusBarComponentElement;
    }
}
declare namespace LocalJSX {
    interface StatusBarComponent {
        "height"?: string;
        "width"?: string;
    }
    interface IntrinsicElements {
        "status-bar-component": StatusBarComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "status-bar-component": LocalJSX.StatusBarComponent & JSXBase.HTMLAttributes<HTMLStatusBarComponentElement>;
        }
    }
}
