/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ChromePopupComponent {
    }
    interface StatusBarComponent {
        "leagueid": string;
        "sport": string;
        "year": string;
    }
}
declare global {
    interface HTMLChromePopupComponentElement extends Components.ChromePopupComponent, HTMLStencilElement {
    }
    var HTMLChromePopupComponentElement: {
        prototype: HTMLChromePopupComponentElement;
        new (): HTMLChromePopupComponentElement;
    };
    interface HTMLStatusBarComponentElement extends Components.StatusBarComponent, HTMLStencilElement {
    }
    var HTMLStatusBarComponentElement: {
        prototype: HTMLStatusBarComponentElement;
        new (): HTMLStatusBarComponentElement;
    };
    interface HTMLElementTagNameMap {
        "chrome-popup-component": HTMLChromePopupComponentElement;
        "status-bar-component": HTMLStatusBarComponentElement;
    }
}
declare namespace LocalJSX {
    interface ChromePopupComponent {
    }
    interface StatusBarComponent {
        "leagueid"?: string;
        "sport"?: string;
        "year"?: string;
    }
    interface IntrinsicElements {
        "chrome-popup-component": ChromePopupComponent;
        "status-bar-component": StatusBarComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "chrome-popup-component": LocalJSX.ChromePopupComponent & JSXBase.HTMLAttributes<HTMLChromePopupComponentElement>;
            "status-bar-component": LocalJSX.StatusBarComponent & JSXBase.HTMLAttributes<HTMLStatusBarComponentElement>;
        }
    }
}
